import type { Metadata } from "next";
import MarketingPage from "@/components/MarketingPage";
import ProductStatus from "@/components/ui/ProductStatus";
import { pageMetadata } from "@/app/metadata";

export const metadata: Metadata = pageMetadata("About", "Nexus builds intelligent systems around real business operations.", "/about");

export default function AboutPage() {
  return <MarketingPage><section className="mx-auto max-w-6xl px-5 pb-24 pt-20 sm:px-8 sm:pt-28"><div className="max-w-4xl"><p className="nexus-subtle text-xs font-medium uppercase tracking-[0.16em]">About Nexus</p><h1 className="nexus-heading mt-5 font-heading text-5xl font-semibold tracking-[-0.055em] sm:text-6xl">Businesses have software. People still move the work.</h1><div className="nexus-copy mt-8 max-w-3xl space-y-5 text-lg leading-8"><p>Teams still spend enormous time moving information between systems, checking dashboards, answering repetitive questions and making routine decisions.</p><p>Nexus builds intelligence and automation around those operations. AI agents, focused software and computer vision are tools inside that mission—not separate company identities.</p></div></div>
    <section className="mt-20 border-y border-[var(--nexus-border)] py-12" aria-labelledby="vertical-model"><p className="nexus-subtle text-xs font-medium uppercase tracking-[0.16em]">The vertical model</p><h2 className="nexus-heading mt-4 font-heading text-3xl font-medium tracking-[-0.045em]" id="vertical-model">One technology foundation. Different industry workflows.</h2><div className="mt-10 grid gap-3 sm:grid-cols-3"><article className="nexus-card min-h-52 rounded-[var(--nexus-radius-control)] p-5"><ProductStatus status="building" /><h3 className="nexus-heading mt-8 text-lg font-medium">Restaurants</h3><p className="nexus-copy mt-3 text-sm leading-6">The first serious vertical: manager intelligence, guest AI and controlled automation.</p></article><article className="nexus-card min-h-52 rounded-[var(--nexus-radius-control)] p-5"><ProductStatus status="building" /><h3 className="nexus-heading mt-8 text-lg font-medium">Retail</h3><p className="nexus-copy mt-3 text-sm leading-6">Operational intelligence, customer systems and computer-vision products in development.</p></article><article className="nexus-card min-h-52 rounded-[var(--nexus-radius-control)] p-5"><ProductStatus status="later" /><h3 className="nexus-heading mt-8 text-lg font-medium">Fitness & beyond</h3><p className="nexus-copy mt-3 text-sm leading-6">Additional verticals are explored only when the workflow and product fit are clear.</p></article></div></section>
    <div className="mt-16 max-w-3xl"><p className="nexus-heading text-xl font-medium">Build from operational truth.</p><p className="nexus-copy mt-4 text-base leading-7">Nexus does not claim a large deployment footprint, universal integrations or one product that fits every business. Each system begins with the real workflow, the people responsible and the controls the operation requires.</p></div>
  </section></MarketingPage>;
}
