import type { Metadata } from "next";
import MarketingPage from "@/components/MarketingPage";
import { pageMetadata } from "@/app/metadata";

export const metadata: Metadata = pageMetadata("About", "Why Nexus builds intelligence, automation, and focused software around real business operations.", "/about");

export default function AboutPage() {
  return <MarketingPage><section className="mx-auto max-w-5xl px-5 pb-24 pt-20 sm:px-8 sm:pt-28"><p className="nexus-subtle text-xs font-medium uppercase tracking-[0.16em]">About Nexus</p><h1 className="nexus-heading mt-5 max-w-4xl font-heading text-5xl font-semibold tracking-[-0.055em] sm:text-6xl">Build intelligence around the business—not the other way around.</h1><div className="nexus-copy mt-10 max-w-3xl space-y-6 text-lg leading-8"><p>Nexus designs applied intelligence, automation, and focused software around work a team already understands: the systems they use, decisions they repeat, information they trust, and moments where human judgment matters.</p><p>The live Nexus Agent proves one part of that model through grounded multilingual conversations, memory, visible workflow events, and Calendar actions. Restaurant manager intelligence, broader integrations, and computer-vision products are being developed deliberately and are labeled as such.</p><p>We do not position every implementation as a chatbot or ask a business to replace its entire technology stack. The goal is to create a useful operating layer where disconnected activity becomes clear, controlled work.</p></div><div className="mt-14 grid gap-3 sm:grid-cols-3">{[["01", "Start with operational truth"], ["02", "Keep people in control"], ["03", "Build only what creates leverage"]].map(([number, text]) => <div className="nexus-card min-h-40 rounded-[var(--nexus-radius-control)] p-5" key={number}><span className="nexus-subtle text-xs">{number}</span><p className="nexus-heading mt-12 text-sm font-medium">{text}</p></div>)}</div></section></MarketingPage>;
}
