import type { Metadata } from "next";
import Link from "next/link";

import { pageMetadata } from "@/app/metadata";
import MarketingPage from "@/components/MarketingPage";
import CraveItSystemMap from "@/components/restaurants/CraveItSystemMap";
import ManagerCommandCenter from "@/components/restaurants/ManagerCommandCenter";
import RestaurantArchitecture from "@/components/restaurants/RestaurantArchitecture";
import RestaurantWorkflowDemo from "@/components/restaurants/RestaurantWorkflowDemo";
import ProductStatus, { type ProductStatusValue } from "@/components/ui/ProductStatus";

export const metadata: Metadata = pageMetadata("Restaurant Intelligence", "Manager intelligence, guest AI and controlled automation across the systems a restaurant already uses.", "/restaurants");

const capabilities = [
  { title: "Manager Intelligence", status: "building" as ProductStatusValue, description: "Bring attention, approvals and daily operating signals into one manager view." },
  { title: "Guest AI", status: "live" as ProductStatusValue, description: "Answer grounded questions in English, Arabic and Turkish, with memory and Calendar reservations." },
  { title: "Approval Inbox", status: "building" as ProductStatusValue, description: "Hold consequential recommendations for a manager before anything is executed." },
  { title: "Automation & Handoff", status: "building" as ProductStatusValue, description: "Route each workflow through AUTO, APPROVAL or HUMAN control." },
] as const;

const implementation = ["Connect", "Configure", "Automate", "Improve"] as const;
type RestaurantsPageProps = { searchParams: Promise<Record<string, string | string[] | undefined>> };
function firstValue(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] : value; }
function contactHref(params: Record<string, string | string[] | undefined>) { const query = new URLSearchParams({ industry: "restaurants", source_page: "/restaurants" }); for (const key of ["utm_source", "utm_medium", "utm_campaign"] as const) { const value = firstValue(params[key])?.slice(0, 100); if (value) query.set(key, value); } return `/contact?${query.toString()}`; }

export default async function RestaurantsPage({ searchParams }: RestaurantsPageProps) {
  const contact = contactHref(await searchParams);
  return <MarketingPage>
    <section className="px-5 pb-24 pt-20 sm:px-8 sm:pb-28 sm:pt-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.08fr_0.92fr] lg:items-end lg:gap-16"><div><div className="flex flex-wrap items-center gap-3"><p className="nexus-subtle text-xs font-medium uppercase tracking-[0.17em]">Nexus for restaurants</p><ProductStatus status="building" /></div><h1 className="nexus-heading mt-5 max-w-5xl font-heading text-5xl font-semibold leading-[0.98] tracking-[-0.06em] sm:text-6xl lg:text-[4.5rem]">Your restaurant already has software. Nexus makes it work together.</h1><p className="nexus-copy mt-7 max-w-2xl text-lg leading-8">Nexus sits above the tools you already use—understanding activity, coordinating approved workflows and giving managers one clear view of what needs attention.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link className="nexus-button-primary nexus-focus inline-flex min-h-12 items-center justify-center rounded-[var(--nexus-radius-control)] px-5 text-sm font-medium" href={contact}>Discuss your restaurant <span aria-hidden="true" className="ms-2">→</span></Link><Link className="nexus-button-secondary nexus-focus inline-flex min-h-12 items-center justify-center rounded-[var(--nexus-radius-control)] px-5 text-sm font-medium" href="/demo/restaurant">Try the live Guest Agent</Link></div></div><aside className="nexus-frame rounded-[var(--nexus-radius-surface)] p-1"><div className="nexus-surface rounded-[calc(var(--nexus-radius-surface)-0.3rem)] p-6 sm:p-7"><div className="flex items-center justify-between border-b border-[var(--nexus-border)] pb-5"><p className="nexus-subtle text-xs font-medium uppercase tracking-[0.15em]">Manager view</p><span className="nexus-subtle text-[10px] uppercase tracking-[0.12em]">One operating layer</span></div><div className="mt-6 space-y-2">{[["Needs attention", "02"], ["Waiting for approval", "01"], ["Nexus handled", "08"]].map(([label, count]) => <div className="nexus-control flex min-h-16 items-center justify-between rounded-xl px-4" key={label}><span className="nexus-heading text-sm font-medium">{label}</span><span className="nexus-subtle text-xs tabular-nums">{count}</span></div>)}</div><p className="nexus-copy mt-5 text-xs leading-5">Illustrative interface. Connected sources and actions are configured per restaurant.</p></div></aside></div></section>

    <section className="border-y border-[var(--nexus-border)] bg-[var(--nexus-surface-soft)] px-5 py-24 sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl"><div className="grid gap-6 lg:grid-cols-[0.75fr_1.25fr] lg:items-end"><div><p className="nexus-subtle text-xs font-medium uppercase tracking-[0.16em]">Existing systems → Nexus</p><h2 className="nexus-heading mt-4 font-heading text-4xl font-semibold tracking-[-0.055em] sm:text-5xl">Keep the tools. Connect the operation.</h2></div><p className="nexus-copy max-w-2xl text-base leading-7 lg:justify-self-end">POS, delivery, messages, reservations and reviews remain systems of record. Nexus turns their enabled activity into decisions and controlled work.</p></div><div className="mt-12"><RestaurantArchitecture /></div></div></section>

    <section className="px-5 py-24 sm:px-8 sm:py-32" id="operating-flow"><div className="mx-auto max-w-7xl"><div className="max-w-4xl"><p className="nexus-subtle text-xs font-medium uppercase tracking-[0.16em]">Restaurant operating flow</p><h2 className="nexus-heading mt-4 font-heading text-4xl font-semibold tracking-[-0.055em] sm:text-5xl">From outside activity to the right next action.</h2><p className="nexus-copy mt-5 max-w-2xl text-base leading-7">Choose a scenario. Live and concept flows are labeled separately.</p></div><div className="mt-12"><RestaurantWorkflowDemo /></div></div></section>

    <section className="border-y border-[var(--nexus-border)] bg-[var(--nexus-surface-soft)] px-5 py-24 sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl"><div className="grid gap-6 lg:grid-cols-[0.78fr_1.22fr] lg:items-end"><div><p className="nexus-subtle text-xs font-medium uppercase tracking-[0.16em]">Manager Command Center</p><h2 className="nexus-heading mt-4 font-heading text-4xl font-semibold tracking-[-0.055em] sm:text-5xl">Know what needs attention.</h2></div><p className="nexus-copy max-w-2xl text-base leading-7 lg:justify-self-end">One concise view for open work, approvals, handled activity and the daily brief.</p></div><div className="mt-12"><ManagerCommandCenter /></div></div></section>

    <section className="px-5 py-24 sm:px-8 sm:py-32"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="nexus-subtle text-xs font-medium uppercase tracking-[0.16em]">Restaurant V1</p><h2 className="nexus-heading mt-4 font-heading text-4xl font-semibold tracking-[-0.055em] sm:text-5xl">Four capabilities. One manager-first system.</h2></div><div className="mt-12 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{capabilities.map((item, index) => <article className="nexus-card flex min-h-72 flex-col rounded-[var(--nexus-radius-surface)] p-6" key={item.title}><div className="flex items-start justify-between gap-3"><span className="nexus-subtle text-xs tabular-nums">0{index + 1}</span><ProductStatus status={item.status} /></div><h3 className="nexus-heading mt-10 font-heading text-xl font-medium tracking-[-0.03em]">{item.title}</h3><p className="nexus-copy mt-4 text-sm leading-6">{item.description}</p></article>)}</div></div></section>

    <section className="border-y border-[var(--nexus-border)] bg-[var(--nexus-surface-soft)] px-5 py-24 sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="nexus-subtle text-xs font-medium uppercase tracking-[0.16em]">Real proof</p><h2 className="nexus-heading mt-4 font-heading text-4xl font-semibold tracking-[-0.055em] sm:text-5xl">Two systems you can inspect today.</h2></div><div className="mt-12 grid gap-4 lg:grid-cols-2"><article className="nexus-card flex min-h-80 flex-col rounded-[var(--nexus-radius-surface)] p-6"><div className="flex justify-between gap-3"><span className="nexus-subtle text-xs">Nexus Guest Agent</span><ProductStatus status="live" /></div><h3 className="nexus-heading mt-10 font-heading text-2xl font-medium tracking-[-0.04em]">Restaurant Agent</h3><p className="nexus-copy mt-4 max-w-xl text-sm leading-6">Grounded guest answers, multilingual conversations, memory and the verified Calendar reservation flow.</p><Link className="nexus-focus mt-auto border-t border-[var(--nexus-border)] pt-5 text-sm font-medium text-[var(--nexus-text)]" href="/demo/restaurant">Try the live workspace <span aria-hidden="true">→</span></Link></article><article className="nexus-frame rounded-[var(--nexus-radius-surface)] p-1"><div className="nexus-surface flex h-full flex-col rounded-[calc(var(--nexus-radius-surface)-0.3rem)] p-6"><div className="flex justify-between gap-3"><span className="nexus-subtle text-xs">Nexus Direct implementation</span><ProductStatus status="live" /></div><h3 className="nexus-heading mt-10 font-heading text-2xl font-medium tracking-[-0.04em]">Crave It</h3><p className="nexus-copy mt-4 max-w-xl text-sm leading-6">A focused customer and operational system for a direct food-business workflow.</p><div className="mt-8"><CraveItSystemMap /></div><Link className="nexus-focus mt-auto border-t border-[var(--nexus-border)] pt-5 text-sm font-medium text-[var(--nexus-text)]" href="/case-studies/crave-it">View the case study <span aria-hidden="true">→</span></Link></div></article></div></div></section>

    <section className="px-5 py-24 sm:px-8 sm:py-32"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-[0.72fr_1.28fr] lg:items-end"><div><p className="nexus-subtle text-xs font-medium uppercase tracking-[0.16em]">Working with Nexus</p><h2 className="nexus-heading mt-4 font-heading text-4xl font-semibold tracking-[-0.055em]">Start with your actual operation.</h2></div><p className="nexus-copy max-w-xl text-base leading-7 lg:justify-self-end">Every restaurant starts with different systems, policies and constraints.</p></div><ol className="mt-12 grid gap-3 lg:grid-cols-4">{implementation.map((step, index) => <li className="nexus-card flex min-h-36 flex-col justify-between rounded-[var(--nexus-radius-control)] p-5" key={step}><span className="nexus-subtle text-xs">0{index + 1}</span><span className="nexus-heading text-sm font-medium">{step}</span></li>)}</ol></div></section>

    <section className="px-5 pb-24 sm:px-8 sm:pb-32"><div className="nexus-frame mx-auto max-w-7xl rounded-[var(--nexus-radius-surface)] p-1"><div className="nexus-surface rounded-[calc(var(--nexus-radius-surface)-0.3rem)] px-6 py-16 text-center sm:px-10 sm:py-20"><p className="nexus-subtle text-xs font-medium uppercase tracking-[0.16em]">Nexus for restaurants</p><h2 className="nexus-heading mx-auto mt-5 max-w-4xl font-heading text-4xl font-semibold tracking-[-0.055em] sm:text-5xl">Where does work get stuck?</h2><p className="nexus-copy mx-auto mt-5 max-w-2xl text-base leading-7">We will map the systems you use, the decisions managers repeat and the safest first workflow.</p><Link className="nexus-button-primary nexus-focus mt-9 inline-flex min-h-12 items-center justify-center rounded-[var(--nexus-radius-control)] px-5 text-sm font-medium" href={contact}>Talk to Nexus <span aria-hidden="true" className="ms-2">→</span></Link></div></div></section>
  </MarketingPage>;
}
