"use client";

import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { useId, useState } from "react";
import ProductStatus, { type ProductStatusValue } from "@/components/ui/ProductStatus";

type Scenario = { id: string; label: string; status: ProductStatusValue; source: string; activity: string; direction?: "rtl"; signals: Array<[string, string]>; destination: string; result: string; note: string };

const scenarios: Scenario[] = [
  { id: "guest-question", label: "Guest question", status: "live", source: "Website message", activity: "هل المطعم مفتوح بعد الساعة العاشرة؟", direction: "rtl", signals: [["Language", "Arabic"], ["Intent", "Opening hours"], ["Knowledge", "Business information"], ["Policy", "Automatic answer"]], destination: "Guest", result: "A grounded answer is prepared in the guest’s language.", note: "Available in the live restaurant workspace." },
  { id: "complaint", label: "Review & complaint", status: "building", source: "Review signal", activity: "My delivery arrived late and the order was incomplete.", signals: [["Signal", "Service complaint"], ["Priority", "Needs attention"], ["Context", "Order reference required"], ["Policy", "Manager approval"]], destination: "Manager", result: "The issue is summarized and held for a manager decision.", note: "Concept workflow. Review integration is not live." },
  { id: "reservation", label: "Reservation", status: "live", source: "Guest request", activity: "I’d like a table for four on Friday at 7 PM.", signals: [["Intent", "Reservation"], ["Details", "Party, date and time"], ["Policy", "Confirmation required"], ["Action", "Calendar workflow"]], destination: "Guest & team", result: "The verified scheduling flow gathers confirmation before creating the event.", note: "Available in the live restaurant workspace." },
  { id: "manager-brief", label: "Manager brief", status: "building", source: "Operating signals", activity: "Reservations, unresolved guest messages and review activity.", signals: [["Window", "Today"], ["Attention", "Open items"], ["Approvals", "Awaiting decision"], ["Output", "Manager summary"]], destination: "Manager", result: "A concise brief groups what needs attention without hiding the source.", note: "Concept preview. Connected operating feeds are being built." },
];

export default function RestaurantWorkflowDemo() {
  const [activeId, setActiveId] = useState(scenarios[0].id);
  const reducedMotion = useReducedMotion();
  const groupId = useId();
  const active = scenarios.find((scenario) => scenario.id === activeId) ?? scenarios[0];
  const transition = { duration: reducedMotion ? 0 : 0.28, ease: [0.22, 1, 0.36, 1] as const };
  function moveFocus(index: number) { const next = scenarios[(index + scenarios.length) % scenarios.length]; setActiveId(next.id); document.getElementById(`${groupId}-${next.id}`)?.focus(); }

  return <div>
    <div aria-label="Restaurant operating scenarios" className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4" role="tablist">
      {scenarios.map((scenario, index) => { const selected = scenario.id === active.id; return <button aria-controls={`${groupId}-panel`} aria-selected={selected} className={`nexus-focus rounded-[var(--nexus-radius-control)] border px-4 py-4 text-start transition ${selected ? "border-[var(--nexus-border-strong)] bg-[var(--nexus-surface-raised)]" : "border-[var(--nexus-border)] bg-[var(--nexus-surface-soft)] hover:border-[var(--nexus-border-strong)]"}`} id={`${groupId}-${scenario.id}`} key={scenario.id} onClick={() => setActiveId(scenario.id)} onKeyDown={(event) => { if (event.key === "ArrowRight" || event.key === "ArrowDown") { event.preventDefault(); moveFocus(index + 1); } if (event.key === "ArrowLeft" || event.key === "ArrowUp") { event.preventDefault(); moveFocus(index - 1); } }} role="tab" tabIndex={selected ? 0 : -1} type="button"><span className="flex items-center justify-between gap-3"><span className="nexus-heading text-sm font-medium">{scenario.label}</span><ProductStatus status={scenario.status} /></span></button>; })}
    </div>
    <div className="nexus-frame mt-4 rounded-[var(--nexus-radius-surface)] p-1"><AnimatePresence initial={false} mode="wait"><motion.div animate={{ opacity: 1, y: 0 }} className="nexus-surface grid min-h-[29rem] rounded-[calc(var(--nexus-radius-surface)-0.3rem)] p-5 lg:grid-cols-[0.83fr_auto_1.34fr_auto_0.83fr] lg:p-7" exit={{ opacity: 0, y: reducedMotion ? 0 : 5 }} id={`${groupId}-panel`} initial={{ opacity: 0, y: reducedMotion ? 0 : 5 }} key={active.id} role="tabpanel" transition={transition}>
      <motion.section animate={{ opacity: 1, x: 0 }} className="nexus-control rounded-[var(--nexus-radius-control)] p-5" initial={{ opacity: 0, x: reducedMotion ? 0 : -8 }} transition={{ ...transition, delay: reducedMotion ? 0 : 0.04 }}><p className="nexus-subtle text-[10px] font-medium uppercase tracking-[0.16em]">External activity</p><p className="nexus-heading mt-3 text-sm font-medium">{active.source}</p><blockquote className="nexus-copy mt-8 border-s border-[var(--nexus-border-strong)] ps-4 text-sm leading-7" dir={active.direction}>{active.activity}</blockquote></motion.section>
      <div aria-hidden="true" className="flex h-10 items-center justify-center lg:h-auto"><motion.span animate={reducedMotion ? undefined : { opacity: [0.25, 1, 0.25] }} className="h-6 w-px bg-[var(--nexus-border-strong)] lg:h-px lg:w-8" transition={{ duration: 1.8, repeat: Infinity }} /></div>
      <motion.section animate={{ opacity: 1, y: 0 }} className="rounded-[var(--nexus-radius-control)] border border-[var(--nexus-border-strong)] bg-[var(--nexus-surface-raised)] p-5 sm:p-6" initial={{ opacity: 0, y: reducedMotion ? 0 : 8 }} transition={{ ...transition, delay: reducedMotion ? 0 : 0.12 }}><div className="flex items-start justify-between gap-4"><div><p className="nexus-subtle text-[10px] font-medium uppercase tracking-[0.17em]">Nexus intelligence</p><h3 className="nexus-heading mt-2 font-heading text-xl font-medium tracking-[-0.03em]">Understand. Decide. Route.</h3></div><ProductStatus status={active.status} /></div><dl className="mt-7 space-y-2">{active.signals.map(([label, value], index) => <motion.div animate={{ opacity: 1, x: 0 }} className="flex min-h-12 items-center justify-between gap-4 rounded-xl border border-[var(--nexus-border)] bg-[var(--nexus-surface-soft)] px-4" initial={{ opacity: 0, x: reducedMotion ? 0 : -6 }} key={label} transition={{ ...transition, delay: reducedMotion ? 0 : 0.18 + index * 0.07 }}><dt className="nexus-subtle text-xs">{label}</dt><dd className="nexus-heading text-right text-xs font-medium">{value}</dd></motion.div>)}</dl></motion.section>
      <div aria-hidden="true" className="flex h-10 items-center justify-center lg:h-auto"><motion.span animate={reducedMotion ? undefined : { opacity: [0.25, 1, 0.25] }} className="h-6 w-px bg-[var(--nexus-border-strong)] lg:h-px lg:w-8" transition={{ delay: 0.4, duration: 1.8, repeat: Infinity }} /></div>
      <motion.section animate={{ opacity: 1, x: 0 }} className="nexus-control rounded-[var(--nexus-radius-control)] p-5" initial={{ opacity: 0, x: reducedMotion ? 0 : 8 }} transition={{ ...transition, delay: reducedMotion ? 0 : 0.38 }}><p className="nexus-subtle text-[10px] font-medium uppercase tracking-[0.16em]">Destination</p><p className="nexus-heading mt-3 text-sm font-medium">{active.destination}</p><p className="nexus-copy mt-8 text-sm leading-7">{active.result}</p><p className="nexus-subtle mt-8 border-t border-[var(--nexus-border)] pt-4 text-xs leading-5">{active.note}</p></motion.section>
    </motion.div></AnimatePresence></div>
  </div>;
}
